import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Naresh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./code.png" />
      </Head>
      <main>
       <div>
        <section className=' flex min-h-screen bg-blue-900'></section>
       </div>
      </main>
    </>
  )
}
